baseURL = "https://wzy816.github.io/blog"

title = "z blog"
copyright = "cc by-nc-sa 4.0"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableEmoji = true

titleCaseStyle = "none"

[outputs]
home = ['html', 'rss']
section = ['html']
taxonomy = ['html']
term = ['html']

[params]
mode = "light"
subtitle = "excerpts and reflections, deviant ideas and intrusive thoughts."
mathjax = true
favicon = "favicon.ico"

[params.author]
name = 'z'
email = 'wzy816@gmail.com'

[frontmatter]
date = ["lastmod", "date"]

[services.rss]
limit = 7

[permalinks]
posts = "/:year/:month/:slug/"

[taxonomies]
series = 'series'
